/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CcCard: typeof import('./src/components/card/CcCard.vue')['default']
    CfcClock: typeof import('./src/components/flip-clock/CfcClock.vue')['default']
    CfcSetBox: typeof import('./src/components/flip-clock/CfcSetBox.vue')['default']
    CfcSlider: typeof import('./src/components/flip-clock/CfcSlider.vue')['default']
    CfcTimePicker: typeof import('./src/components/flip-clock/CfcTimePicker.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElStatistic: typeof import('element-plus/es')['ElStatistic']
    ElTag: typeof import('element-plus/es')['ElTag']
    FileUpload: typeof import('./src/components/buttons/FileUpload.vue')['default']
    GoBack: typeof import('./src/components/buttons/GoBack.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/svg-icon/SvgIcon.vue')['default']
    ToggleButton: typeof import('./src/components/toggle-switch/toggle-button.vue')['default']
    ToggleSwitch: typeof import('./src/components/toggle-switch/ToggleSwitch.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
